app:
  name: spring-cert-client
  description: Client for spring-cert

server:
  port: 8090

spring:
  profiles:
    active: default

---
spring:
  profiles: default

endpoint:
  scheme: http
  host: localhost
  port: 8080

---
spring:
  profiles: cloud

endpoint:
  scheme: https
  host: springcert-brave-manatee-ij.cfapps.io
  port: null
